version: '3.1'
services:

  statistic-server:
    build: ewm-statistic
    image: statistic-server_image
    container_name: statistic-server_container
    ports:
      - "9090:9090"
    depends_on:
      - statistic-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://statistic-db:5432/ewm-statistic-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

  statistic-db:
    image: postgres:15-alpine
    container_name: statistic-db_container
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=ewm-statistic-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
#    - TZ=Europe/Moscow

  ewm-service:
    build: ewm-service
    image: ewm-service-image
    container_name: ewm-service-container
    ports:
      - "8080:8080"
    depends_on:
      - service-db
      - statistic-server
    environment:
      - statistic-server.url=http://statistic-server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db:5432/ewm-service-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=1234

  service-db:
    image: postgres:14.3-alpine
    container_name: ewm-service-db-container
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm-service-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234
#     - TZ=Europe/Moscow