CREATE TABLE IF NOT EXISTS hits (
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    app varchar(255) NOT NULL,
    uri varchar(255) NOT NULL,
    ip varchar(15) NOT NULL,
    time_stamp TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_hits PRIMARY KEY (id)
);